server/webapp/WEB-INF/rails.new/config/routes.rb
##########################GO-LICENSE-END##################################

Go::Application.routes.draw do
  mount JasmineRails::Engine => '/jasmine-specs', as: :jasmine_old if defined?(JasmineRails)
  mount JasmineRails::Engine => '/jasmine-specs-new', as: :jasmine_new if defined?(JasmineRails)

  unless defined?(CONSTANTS)
    ELASTIC_AGENT_PROFILE_ID_FORMAT = USER_NAME_FORMAT = GROUP_NAME_FORMAT = TEMPLATE_NAME_FORMAT = PIPELINE_NAME_FORMAT = STAGE_NAME_FORMAT = ENVIRONMENT_NAME_FORMAT = /[\w\-][\w\-.]*/
    JOB_NAME_FORMAT = /[\w\-.]+/
    PIPELINE_COUNTER_FORMAT = STAGE_COUNTER_FORMAT = /-?\d+/
    NON_NEGATIVE_INTEGER = /\d+/
    PIPELINE_LOCATOR_CONSTRAINTS = {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}
    STAGE_LOCATOR_CONSTRAINTS = {:stage_name => STAGE_NAME_FORMAT, :stage_counter => STAGE_COUNTER_FORMAT}.merge(PIPELINE_LOCATOR_CONSTRAINTS)
    ENVIRONMENT_NAME_CONSTRAINT = {:name => ENVIRONMENT_NAME_FORMAT}
    PLUGIN_ID_FORMAT = /[\w\-.]+/
    ALLOW_DOTS = /[^\/]+/
    CONSTANTS = true
  end

  mount Oauth2Provider::Engine => '/oauth', :as => :oauth_engine

  root 'welcome#index' # put to get root_path. '/' is handled by java.

  get "about", controller: :about, action: :show, as: :about

  get "admin/pipelines/snippet" => "admin/pipelines_snippet#index", as: :pipelines_snippet
  get "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_show
  get "admin/pipelines/snippet/:group_name/edit" => "admin/pipelines_snippet#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_edit
  put "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_update

  get 'admin/backup' => 'admin/backup#index', as: :backup_server
  post 'admin/backup' => 'admin/backup#perform_backup', as: :perform_backup

  get "admin/plugins" => "admin/plugins/plugins#index", as: :plugins_listing
  post 'admin/plugins' => 'admin/plugins/plugins#upload', as: :upload_plugin
  get 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#edit_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :edit_settings
  post 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#update_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :update_settings

  ["svn", "git", "hg", "p4", "dependency", "tfs", "package"].each do |material_type|
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/new" => "admin/materials/#{material_type}#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_new"
    post "admin/pipelines/:pipeline_name/materials/#{material_type}" => "admin/materials/#{material_type}#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_create"
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print/edit" => "admin/materials/#{material_type}#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_edit"
    put "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print" => "admin/materials/#{material_type}#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_update"
  end
  defaults :no_layout => true do
    get "admin/pipelines/:pipeline_name/materials/dependency/pipeline_name_search" => "admin/materials/dependency#pipeline_name_search", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_pipeline_name_search
    get "admin/pipelines/:pipeline_name/materials/dependency/load_stage_names_for" => "admin/materials/dependency#load_stage_names_for", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_load_stage_names_for
  end
  get "admin/:stage_parent/:pipeline_name/materials" => "admin/materials#index", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_index
  delete "admin/:stage_parent/:pipeline_name/materials/:finger_print" => "admin/materials#destroy", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_delete

  get "admin/pipeline/new" => "admin/pipelines#new", as: :pipeline_new
  post "admin/pipelines" => "admin/pipelines#create", as: :pipeline_create
  get "admin/pipeline/:pipeline_name/clone" => "admin/pipelines#clone", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pipeline_clone
  post "admin/pipeline/save_clone" => "admin/pipelines#save_clone", as: :pipeline_save_clone
  get "admin/pipelines/:pipeline_name/pause_info.json" => "admin/pipelines#pause_info", :format => "json", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pause_info_refresh
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#edit", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#update", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_update

  get "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_listing
  put "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#use_template", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_use_template
  get "admin/:stage_parent/:pipeline_name/stages/new" => "admin/stages#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_new
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name" => "admin/stages#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_delete
  post "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/increment" => "admin/stages#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_edit
  #put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT,  stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update

  get "admin/commands" => "admin/commands#index", as: :admin_commands
  get "admin/commands/show" => "admin/commands#show", as: :admin_command_definition

server/webapp/WEB-INF/rails.new/app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" lang='en'>

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=9">
  <%- @current_tab_name = "admin" -%>
  <%- @view_title = @view_title || "Administration" -%>
  <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
  <div id="body_bg">
    <div id="header">
      <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
      <div class="messaging_wrapper" id="messaging_wrapper">
        <%= render :partial => "shared/flash_message" %>
        <%= render :partial => "shared/config_save_actions", :locals => {:scope => {}} -%>
      </div>

      <% if @in_pipeline_group_edit %>
          <div class="page_header">
            <div class="row">
              <h1 id="page-title" class="entity_title">
                <%= link_to l.string("ADMINISTRATION"), main_app.pipeline_groups_path -%>&nbsp;&raquo;
                <%= link_to l.string("PIPELINE_GROUPS"), main_app.pipeline_groups_path -%>&nbsp;&raquo;
                <%= @group.getGroup() -%>
              </h1>
            </div>
          </div>
      <% else %>
          <div class="page_header">
            <div class="row">
              <h1 id="page-title" class="entity_title"><%= l.string("ADMINISTRATION") -%></h1>
            </div>
          </div>
      <%- end -%>

      <% unless @config_valid %>
          <%== flash_message_pane_start("config_error", false) %>
          <p class="warning"><%= l.string("INVALID_CONFIG_ON_DISK") -%></p>
          <%== flash_message_pane_end %>
      <% end %>

      <%== content_wrapper_tag %>
      <div class="row">
        <div class="bd-container rounded-corner-for-pipeline admin-rounded-container">
          <div class="sub_tab_container rounded-corner-for-tab-container">
            <div class="sub_tabs_container">
              <ul>
                <% if is_user_an_admin? || is_user_a_group_admin? %>
                    <li id="pipeline-groups-tab-button" class="<%= "current_tab" if @tab_name == "pipeline-groups" %>">
                      <a id="tab-link-of-pipeline-groups" href="<%= main_app.pipeline_groups_path -%>"><%= l.string("PIPELINES_POPUP_TITLE") -%></a>
                    </li>
                <% end %>
                <% if is_user_an_admin? || is_user_a_template_admin? -%>
                    <li id="templates-tab-button" class="<%= "current_tab" if @tab_name == "templates" %>">
                      <a id="tab-link-of-templates" href="<%= main_app.templates_path -%>"><%= l.string("TEMPLATES") -%></a>
                    </li>
                <%- end -%>
                <% if !is_user_an_admin? && is_user_a_group_admin? %>
                    <li id="tab-content-of-pipelines-snippet" class="<%= "current_tab" if @tab_name == "pipelines-snippet" %>">
                      <%= link_to l.string("PIPELINES_SNIPPET"), main_app.pipelines_snippet_path, :id => "tab-link-of-pipelines-snippet" -%>
                    </li>
                    <% if is_plugins_enabled? %>
                        <li id="plugins-listing-tab-button" class="<%= @tab_name == "plugins-listing" ? "current_tab" : "" -%>">
                          <%= link_to l.string("PLUGINS_TAB"), main_app.plugins_listing_path, :id => "tab-link-of-plugins-listing" %>
                        </li>
                    <% end %>
                    <li id="package-repositories-tab-button" class="<%= @tab_name == "package-repositories" ? "current_tab" : "" -%>">
                      <%= link_to l.string("PACKAGE_REPOSITORY_TAB"), main_app.package_repositories_list_path, :id => "tab-link-of-package-repositories" %>
                    </li>
                <% end %>

                <% if is_user_an_admin? %>
                    <li id="source-xml-tab-button" class="<%= "current_tab" if @tab_name == "configuration-xml" %>">
                      <%= link_to l.string("PIPELINES_SNIPPET"), main_app.config_view_path, :id => 'tab-link-of-source-xml' -%>
                    </li>
                    <li id="server-configuration-tab-button" class="<%= "current_tab" if @tab_name == "server_configuration" %>">
                      <%= link_to l.string("SERVER_CONFIGURATION"), main_app.edit_server_config_path, :id => 'tab-link-of-server-configuration' -%>
                    </li>
                    <li id="user-summary-tab-button" class="<%= @tab_name == "user-listing" ? "current_tab" : "" -%>">
                      <%= link_to "User Summary", main_app.user_listing_path, :id => "tab-link-of-user-listing" %>
                    </li>
                    <li id="oauth-clients-tab-button" class="<%= @tab_name == "oauth-clients" ? "current_tab" : "" -%>">
                      <%= link_to "OAuth Clients", oauth_engine.clients_path, :id => "tab-link-of-oauth-clients" %>
                    </li>
                    <li id="backup-tab-button" class="<%= @tab_name == "backup" ? "current_tab" : "" -%>">
                      <%= link_to "Backup", main_app.backup_server_path, :id => "tab-link-of-backup" %>
                    </li>
                    <% if is_plugins_enabled? %>
                        <li id="plugins-listing-tab-button" class="<%= @tab_name == "plugins-listing" ? "current_tab" : "" -%>">
                          <%= link_to l.string("PLUGINS_TAB"), main_app.plugins_listing_path, :id => "tab-link-of-plugins-listing" %>
                        </li>
                    <% end %>
                    <li id="package-repositories-tab-button" class="<%= @tab_name == "package-repositories" ? "current_tab" : "" -%>">
                      <%= link_to l.string("PACKAGE_REPOSITORY_TAB"), main_app.package_repositories_new_path, :id => "tab-link-of-package-repositories" %>
                    </li>
                <% end %>
              </ul>
            </div>
            <div class="sub_tab_container_content admin-tab-contents">
              <div id="tab-content-of-<%= @tab_name -%>" style="">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= end_content_wrapper %>
<div id='footer-new-foundation'>
  <%= render :partial => 'navigation_elements/footer' %>
</div>
</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/agent_detail.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <%- @view_title ||= "Agents" -%>
  <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
  <div id="body_bg">
    <div id="header">
      <%= render :partial => "shared/header" %>
    </div>
    <div id='body_content'>
      <div class="messaging_wrapper" id="messaging_wrapper">
        <%= render :partial => "shared/flash_message" %>
      </div>
      <div class="page_header">
        <div class="row">
          <ul class="entity_title">
            <li class="last"><h1><%= @agent.getHostname() -%></h1></li>
          </ul>
        </div>
      </div>
      <%= content_wrapper_tag %>
      <div class="row">
        <%= yield %>
      </div>
      <%= end_content_wrapper %>
    </div>
  </div>
</div>
<div id='footer-new-foundation'>
  <%= render :partial => 'navigation_elements/footer' %>
</div>

</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" lang='en'>


<head>
    <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
<div id="body_bg">
    <div id="header">
        <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
        <div class="messaging_wrapper" id="messaging_wrapper">
            <%= render :partial => "shared/flash_message" %>
            <%= render :partial => "shared/config_save_actions", :locals => { :scope => {}}-%>
        </div>
        <%= render :partial => "shared/subheader" %>
        <% if @show_environment_breadcrumb %>
            <div id="pipeline_header">
                <div class="entity_status_wrapper page_header ">
                  <div class="row">
                    <ul class="entity_title">
                        <!--<li><%= link_to l.string("ENVIRONMENTS"), environments_path %></li>-->
                        <li class="last"><h1 class="name"><%= @environment.name() -%></h1></li>
                    </ul>
                  </div>
                </div>
            </div>
        <% end %>
        <%= yield %>
    </div>
  </div>
</div>
    <div id='footer-new-foundation'>
        <%= render :partial => 'navigation_elements/footer' %>
    </div>

</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/comparison.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <%- @view_title =  l.string("COMPARE_PIPELINES_PAGE") -%>
    <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
<div id="body_bg">
    <div id="header">
        <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
        <div class="messaging_wrapper" id="messaging_wrapper">
            <%= render :partial => "shared/flash_message" %>
        </div>
        <div id="pipeline_header">
            <div class="entity_status_wrapper page_header">
              <div class="row">
                <%= render :partial => "shared/pipeline_breadcrumb", :locals => {:scope => {:pipeline => @to_pipeline, :third => {:text => l.string("COMPARE")}}} %>
              </div>
              </div>
        </div>
        <%= content_wrapper_tag %>
      <div class="row">
        <div id="pipeline_status_bar" class="pipeline_flow">
            <table>
                <tbody>
                    <tr>
                        <td width="360px" valign="top"><%= render :partial => 'comparison/stage_bar_without_controls.html', :locals => {:scope => {:pipeline => @from_pipeline, :fixed_pipeline => @to_pipeline, :pipeline_instances => @from_pipeline_instances_model, :suffix => "from"}} %></td>
                        <td valign="top"><div class="compared_to"><%= l.string("COMPARED_TO") %></div></td>
                        <td width="360px" valign="top"><%= render :partial => 'comparison/stage_bar_without_controls.html', :locals => {:scope => {:pipeline => @to_pipeline, :fixed_pipeline => @from_pipeline, :pipeline_instances => @to_pipeline_instances_model, :suffix => "to"}} %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <%= yield %>
      </div>
        <%= end_content_wrapper %>
    </div>
  </div>
</div>

    <div id='footer-new-foundation'>
      <%= render :partial => 'navigation_elements/footer' %>
    </div>
</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/my-cruise.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <%- @view_title = l.string("PREFERENCES_LOWER") -%>
  <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
  <div id="body_bg">

    <div id="header">
      <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
      <div class="messaging_wrapper" id="messaging_wrapper">
        <%= render :partial => "shared/flash_message" %>
      </div>

      <div class="page_header">
        <div class="row">
        <h1 class="entity_title"><%= l.string("PREFERENCES_LOWER") %></h1>
      </div>
    </div>

    <div class="bd-container rounded-corner-for-pipeline admin-rounded-container row">
      <b class="c1"></b><b class="c2"></b><b class="c3"></b><b class="c4"></b>

      <div class="sub_tab_container rounded-corner-for-tab-container">
        <b class="c1"></b><b class="c2"></b><b class="c3"></b><b class="c4"></b>

        <div class="sub_tabs_container">
          <ul>
            <li>
              <%= link_to l.string("NOTIFICATIONS_LOWER"), system_environment.pathFor("/tab/mycruise/user") %>
            </li>
            <li class="current_tab">
              <%= link_to l.string("OAUTH_ACCESS_TOKENS"), url_for(:controller => 'user_tokens', :action => :index) %>
            </li>
          </ul>
          <div class="clear"></div>
        </div>
        <div class="sub_tab_container_content">
          <div id="tab-content" class="wizard" style="">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<div id='footer-new-foundation'>
  <%= render :partial => 'navigation_elements/footer' %>
</div>
</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/pipeline_admin.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
  <div id="body_bg">
    <div id="header">
      <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
      <div class="messaging_wrapper" id="messaging_wrapper">
        <%= render :partial => "shared/flash_message" %>
        <%= render :partial => "shared/config_save_actions", :locals => {:scope => {}} -%>
      </div>

      <div id="pause_info_and_controls">
        <%= render :partial => "shared/pause_info_and_control.html", :locals => {:scope => {:pause_info => @pause_info, :pipeline_name => @pipeline.name()}} %>
      </div>

      <div class="page_header">
        <div class="row">
            <h1 class="entity_title">
              <%= link_to l.string("ADMINISTRATION"), pipeline_groups_path -%>
            </h1>
        </div>
      </div>

      <%= yield %>
    </div>
  </div>
</div>
<div id='footer-new-foundation'>
  <%= render :partial => 'navigation_elements/footer' %>
</div>
</body>

<script type="text/javascript">
  AjaxRefreshers.addRefresher(new AjaxRefresher("<%= pause_info_refresh_path(:pipeline_name => @pipeline.name()) -%>"), true);
</script>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/single_page_app.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <title><%= @view_title %> - Go</title>

  <link rel="shortcut icon" href="<%=asset_path('cruise.ico')%>"/>
  <%= stylesheet_link_tag 'frameworks' %>
  <%= stylesheet_link_tag "single_page_apps/#{controller_name}" %>
  <%= requirejs_include_tag "single_page_apps/#{controller_name}" %>
  <%= csrf_meta_tags %>
</head>

<body data-controller-name="<%= controller_name %>" data-action-name="<%= action_name %>" id="<%= controller_name %>-page">
<div class="page-wrap">
  <header class="app-header">
    <div class="row expanded">
      <%= render :partial => 'new_navigation_elements/navigation' %>
    </div>
  </header>

  <main class="main-container">

    <%= yield %>
  </main>

</div>
<%= render :partial => 'new_navigation_elements/footer' %>

</body>
</html>

server/webapp/WEB-INF/rails.new/app/views/layouts/value_stream_map.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" lang='en'>


<head>
  <%= render :partial => "shared/head" %>
</head>
<body id="<%= page_name %>" class="<%= page_name %>">
<div class="page-wrap">
  <div id="body_bg" class="vsm">
    <div id="header">
      <%= render :partial => "shared/header" %>
    </div>

    <div id='body_content'>
      <%= yield %>
    </div>

    <div class='pan' style='display: none;'>
      <div class="constrainer">
        <div class='knob'></div>
      </div>
      <canvas id='canvas'></canvas>
    </div>
  </div>
</div>
  <div id='footer-new-foundation'>
    <%= render :partial => 'navigation_elements/footer' %>
  </div>

<div id='pre-loader-overlay'>
  <div class='loading'></div>
</div>
</body>
</html>