server/webapp/WEB-INF/rails.new/config/routes.rb
##########################GO-LICENSE-START################################
# Copyright 2016 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

Go::Application.routes.draw do
  mount JasmineRails::Engine => '/jasmine-specs', as: :jasmine_old if defined?(JasmineRails)
  mount JasmineRails::Engine => '/jasmine-specs-new', as: :jasmine_new if defined?(JasmineRails)

  unless defined?(CONSTANTS)
    ELASTIC_AGENT_PROFILE_ID_FORMAT = USER_NAME_FORMAT = GROUP_NAME_FORMAT = TEMPLATE_NAME_FORMAT = PIPELINE_NAME_FORMAT = STAGE_NAME_FORMAT = ENVIRONMENT_NAME_FORMAT = /[\w\-][\w\-.]*/
    JOB_NAME_FORMAT = /[\w\-.]+/
    PIPELINE_COUNTER_FORMAT = STAGE_COUNTER_FORMAT = /-?\d+/
    NON_NEGATIVE_INTEGER = /\d+/
    PIPELINE_LOCATOR_CONSTRAINTS = {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}
    STAGE_LOCATOR_CONSTRAINTS = {:stage_name => STAGE_NAME_FORMAT, :stage_counter => STAGE_COUNTER_FORMAT}.merge(PIPELINE_LOCATOR_CONSTRAINTS)
    ENVIRONMENT_NAME_CONSTRAINT = {:name => ENVIRONMENT_NAME_FORMAT}
    PLUGIN_ID_FORMAT = /[\w\-.]+/
    ALLOW_DOTS = /[^\/]+/
    CONSTANTS = true
  end

  mount Oauth2Provider::Engine => '/oauth', :as => :oauth_engine

  root 'welcome#index' # put to get root_path. '/' is handled by java.

  get "about", controller: :about, action: :show, as: :about

  get "admin/pipelines/snippet" => "admin/pipelines_snippet#index", as: :pipelines_snippet
  get "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_show
  get "admin/pipelines/snippet/:group_name/edit" => "admin/pipelines_snippet#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_edit
  put "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_update

  get 'admin/backup' => 'admin/backup#index', as: :backup_server
  post 'admin/backup' => 'admin/backup#perform_backup', as: :perform_backup

  get "admin/plugins" => "admin/plugins/plugins#index", as: :plugins_listing
  post 'admin/plugins' => 'admin/plugins/plugins#upload', as: :upload_plugin
  get 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#edit_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :edit_settings
  post 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#update_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :update_settings

  ["svn", "git", "hg", "p4", "dependency", "tfs", "package"].each do |material_type|
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/new" => "admin/materials/#{material_type}#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_new"
    post "admin/pipelines/:pipeline_name/materials/#{material_type}" => "admin/materials/#{material_type}#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_create"
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print/edit" => "admin/materials/#{material_type}#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_edit"
    put "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print" => "admin/materials/#{material_type}#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_update"
  end
  defaults :no_layout => true do
    get "admin/pipelines/:pipeline_name/materials/dependency/pipeline_name_search" => "admin/materials/dependency#pipeline_name_search", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_pipeline_name_search
    get "admin/pipelines/:pipeline_name/materials/dependency/load_stage_names_for" => "admin/materials/dependency#load_stage_names_for", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_load_stage_names_for
  end
  get "admin/:stage_parent/:pipeline_name/materials" => "admin/materials#index", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_index
  delete "admin/:stage_parent/:pipeline_name/materials/:finger_print" => "admin/materials#destroy", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_delete

  get "admin/pipeline/new" => "admin/pipelines#new", as: :pipeline_new
  post "admin/pipelines" => "admin/pipelines#create", as: :pipeline_create
  get "admin/pipeline/:pipeline_name/clone" => "admin/pipelines#clone", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pipeline_clone
  post "admin/pipeline/save_clone" => "admin/pipelines#save_clone", as: :pipeline_save_clone
  get "admin/pipelines/:pipeline_name/pause_info.json" => "admin/pipelines#pause_info", :format => "json", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pause_info_refresh
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#edit", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#update", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_update

  get "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_listing
  put "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#use_template", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_use_template
  get "admin/:stage_parent/:pipeline_name/stages/new" => "admin/stages#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_new
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name" => "admin/stages#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_delete
  post "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/increment" => "admin/stages#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete

server/webapp/WEB-INF/rails.new/app/controllers/api/stages_controller.rb
##########################GO-LICENSE-START################################
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

java_import 'org.springframework.dao.DataRetrievalFailureException'

class Api::StagesController < Api::ApiController
  include ApplicationHelper

  def index
    return render_not_found unless number?(params[:id])

    stage_id = Integer(params[:id])
    begin
      @stage = stage_service.stageById(stage_id)
      @doc = xml_api_service.write(StageXmlViewModel.new(@stage), "#{request.protocol}#{request.host_with_port}/go")
      respond_to do |format|
        format.xml
      end
    rescue Exception => e
      logger.error(e)
      return render_not_found
    end
  end

  def cancel
    stage_id = Integer(params[:id])
    result = HttpLocalizedOperationResult.new
    schedule_service.cancelAndTriggerRelevantStages(stage_id, current_user, result)
    render_localized_operation_result result
  end

  def cancel_stage_using_pipeline_stage_name
    pipeline_name = params[:pipeline_name]
    stage_name = params[:stage_name]
    result = HttpLocalizedOperationResult.new
    schedule_service.cancelAndTriggerRelevantStages(pipeline_name,stage_name, current_user, result)
    render_localized_operation_result result
  end

  def history
    pipeline_name = params[:pipeline_name]
    stage_name = params[:stage_name]
    offset = params[:offset].to_i
    page_size = 10
    stage_instance_count = stage_service.getCount(pipeline_name, stage_name)
    result = HttpOperationResult.new

    pagination = Pagination.pageStartingAt(offset, stage_instance_count, page_size)
    stage_history = stage_service.findDetailedStageHistoryByOffset(pipeline_name, stage_name, pagination, CaseInsensitiveString.str(current_user.getUsername()), result)

    if result.canContinue()
      stage_history_api_model = StageHistoryAPIModel.new(pagination, stage_history)
      render json: stage_history_api_model
    else
      render_error_response(result.detailedMessage(), result.httpCode(), true)
    end
  end

  def instance_by_counter
    pipeline_name = params[:pipeline_name]
    pipeline_counter = params[:pipeline_counter].to_i
    stage_name = params[:stage_name]
    stage_counter = params[:stage_counter]
    result = HttpOperationResult.new

    stage_model = stage_service.findStageWithIdentifier(pipeline_name, pipeline_counter, stage_name, stage_counter, CaseInsensitiveString.str(current_user.getUsername()), result)

    if result.canContinue()
      stage_api_model = StageAPIModel.new(stage_model)
      render json: stage_api_model
    else
      render_error_response(result.detailedMessage(), result.httpCode(), true)
    end
  end

  private
  def render_not_found()
    render text: "Not Found!", status: 404
  end
end

server/webapp/WEB-INF/rails.new/app/helpers/stages_helper.rb
##########################GO-LICENSE-START################################
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

module StagesHelper

  def placeholder_stage? stage
    stage.getState() == com.thoughtworks.go.domain.StageState::Unknown
  end

  def is_current_stage?(identifier)
    params[:pipeline_name] == identifier.getPipelineName() &&
            params[:pipeline_counter].to_i == identifier.getPipelineCounter().to_i &&
            params[:stage_name] == identifier.getStageName() &&
            params[:stage_counter].to_i == identifier.getStageCounter().to_i
  end

  def stage_detail_path_for_identifier(identifier, options = {})
    stage_detail_tab_path(options.merge(:pipeline_name => identifier.getPipelineName(),
                                    :pipeline_counter => identifier.getPipelineCounter(),
                                    :stage_name => identifier.getStageName(),
                                    :stage_counter => identifier.getStageCounter()))
  end

  def stage_detail_pipeline_tab_for_identifier identifier
    tab_aware_path_for_stage identifier, 'pipeline'
  end

  def tab_aware_path_for_stage stage_identifier, tab    
    stage_detail_tab_path :pipeline_name => stage_identifier.getPipelineName(),
                          :pipeline_counter => stage_identifier.getPipelineCounter(),
                          :stage_name => stage_identifier.getStageName(),
                          :stage_counter => stage_identifier.getStageCounter(),
                          :action => tab
  end

  def empty_stage(stage_instance_model)
    stage_instance_model.instance_of? com.thoughtworks.go.presentation.pipelinehistory.NullStageHistoryItem
  end

  def link_with_current_tab(link_name, action)
    class_name = action == params[:action] ? ' class="current"' : ''
    "<li#{class_name}>#{link_to(link_name, stage_detail_tab_path(:action => action))}</li>".html_safe
  end

  def stage_bar_options sim
    tag_options(:class => "stage_bar #{sim.getState()}", :title => "%s (%s)" % [sim.getName(), l.messageFor(sim.getState())])
  end

  def stage_history_pagination_handler page, tab
    dom_id = "stage_history_#{page.getLabel()}"
    url = stage_history_path(:page => page_num=page.getNumber(), :tab => tab)
    <<END
    <a href="#" id="#{dom_id}">#{page.getLabel()}</a>
    <script type="text/javascript">
        StageHistory.bindHistoryLink('##{dom_id}', '#{url}', #{page.getNumber()});
    </script>
END
  end

  def is_config_used_to_run_this_stage_out_of_sync_with_current?(current_config_version, stage_config_version)
    current_config_version != stage_config_version
  end
 end

server/webapp/WEB-INF/rails.new/app/views/admin/stages/_stage_navigation.html.erb
<ul>
    <% default_options = {:pipeline_name => params[:pipeline_name], :stage_name => params[:stage_name]} %>
    <li id="stage"><%= link_to l.string('STAGE_SETTINGS'), admin_stage_edit_path(default_options.merge(:current_tab => "settings", :stage_parent => "pipelines")) %></li>
    <li id="jobs"><%= link_to "#{l.string('JOBS')}", admin_job_listing_path() %></li>
    <!-- fix me, no instance variables should be used in partial, this can lead to crazy production-only bugs -jj -->
    <li id="variables"><%= link_to l.string("ENVIRONMENT_VARIABLES"), admin_stage_edit_path(default_options.merge(:current_tab => "environment_variables", :stage_parent => "pipelines")) %></li>
    <li id="permissions"><%= link_to l.string("PERMISSIONS"), admin_stage_edit_path(default_options.merge(:current_tab => "permissions", :stage_parent =>"pipelines")) %></li>
</ul>

server/webapp/WEB-INF/rails.new/app/views/admin/stages/index.html.erb
<div class="config-container">
<h3><%= l.string("STAGES") %></h3>

<% if (params[:stage_parent] == "pipelines") %>
    <%= form_for @pipeline, :as => :pipeline, :url => admin_stage_listing_path(), :html => {:method => :put, :id => 'pipeline_edit_form'} do |f| %>
        <%= md5_field %>

        <%= render :partial => "admin/shared/stage_configuration_type.html", :locals => {:scope => {:form => f, :pipeline => @pipeline}} -%>
        <div id="select_template_container" class="hidden">
            <% if @template_list.length > 0 %>
                <div class="fieldset">
                    <div class="form_item">

                        <div class="template_selection">
                            <%= f.label l.string("SELECT_TEMPLATE") %>
                            <%= f.select(com.thoughtworks.go.config.PipelineConfig::TEMPLATE_NAME, @template_list, {:selected => @pipeline.getTemplateName()}, {:id => "select_template"}) %>

                            <% template_name = (@pipeline.getTemplateName() || @template_list.first).to_s %>

                            <%= link_to l.string("VIEW"), "#", :class=> "view_template_link action_icon button preview_icon skip_dirty_stop"%>
                            <% if is_user_an_admin? %>
                                <%=link_to l.string("EDIT"), template_edit_path(:pipeline_name => template_name, :stage_parent => "templates", :current_tab => 'general'), :class=> "action_icon edit_icon edit_template_link"%>
                            <% end %>
                        </div>

                    </div>
                </div>
                <div class="form_buttons">
                    <%= submit_button(l.string("SAVE"), :class => 'primary skip_dirty_stop', :id => "submit_pipeline_edit_form", :onclick => "return false;") %>
                    <%= link_to l.string("RESET"), admin_stage_listing_path(:current_tab => "stages"), :class => 'reset_button link_as_button', :id => 'reset_form' -%>
                </div>
            <% else %>
                <div class="no_templates_message information">
                    <%= l.string("NO_TEMPLATES_DEFINED") %>
                </div>
            <% end %>
        </div>

        <script type="text/javascript">
            $('submit_pipeline_edit_form').observe('click', function() {
                Modalbox.show(jQuery('#warning_prompt')[0], {overlayClose: false, title: '<%= l.string("CONFIRM_SAVE") %>'});
            });
        </script>
        <div id="warning_prompt" class="warning" style="display:none;">
            <div class="ui-dialog-content">
                <p>Switching to a template will cause all of the currently defined stages in this pipeline to be lost. Are you sure you want to continue?</p>
            </div>
            <div class="form_buttons actions">
                <%= submit_button(l.string("PROCEED"), :class=> "primary", :onclick => "$('pipeline_edit_form').submit()") %>
                <%= submit_button(l.string("CANCEL"), :onclick => "Modalbox.hide()", :type => "button") %>
            </div>
        </div>

    <% end %>
<% end %>

<% if params[:stage_parent] == "templates" || @pipeline.getConfigurationType == com.thoughtworks.go.config.PipelineConfig::CONFIGURATION_TYPE_STAGES %>
    <div id="stages_list_container">
        <table class="list_table reorderable_table stages_listing">
            <thead>
            <tr>
                <th><%= l.string("ORDER") %></th>
                <th><%= l.string("STAGE") %></th>
                <th><%= l.string("STAGE_TRIGGER_TYPE") %></th>
                <th><%= l.string("JOBS") %></th>
                <th class="remove"><%= l.string("REMOVE") %></th>
            </tr>
            </thead>
            <tbody>
            <% @pipeline.each_with_index do |stage_config, stage_config_index| %>
                <tr class="stage_<%= stage_config.name() %>">
                    <td>
                        <%= form_for stage_config, :as => :stage_config, :url => {:action => "decrement_index", :stage_name => stage_config.name(), :pipeline_name => @pipeline.name(), :type => params[:type]},
                                    :html => {:method => :post} do |f| %>
                            <%= md5_field %>
                            <% unless stage_config_index == 0 %>
                                <button type="submit" value="" class="promote_button" title="<%= l.string("MOVE_STAGE_UP") %>">
                                    <div class="promote_up"></div>
                                </button>
                            <% end %>
                        <% end %>
                        <%= form_for stage_config, :as => :stage_config, :url => {:action => "increment_index", :stage_name => stage_config.name(), :pipeline_name => @pipeline.name(), :type => params[:type]}, :html => {:method => :post} do |f| %>
                            <%= md5_field %>
                            <% unless stage_config_index == @pipeline.size()-1 %>
                                <button type="submit" value="" class="promote_button" title="<%= l.string("MOVE_STAGE_DOWN") %>">
                                    <div class="promote_down"></div>
                                </button>
                            <% end %>
                        <% end %>
                    </td>
                    <td class="stage_name"><%= link_to(stage_config.name(), admin_stage_edit_path(:stage_name => stage_config.name(), :current_tab => "settings"), :class => "stage_name_link") %></td>
                    <td class="approval_type"><%= stage_config.getApproval().getDisplayName() %></td>
                    <td class="number_of_jobs"><%= stage_config.allBuildPlans().size() %></td>
                    <td class="remove">
                        <% if @stage_usage && @stage_usage.contains(stage_config) %>
                            <span class="icon_cannot_remove has_go_tip_right" title="Cannot delete this stage because it is used as a material in other pipelines"></span>
                        <% elsif @pipeline.size() == 1 %>

                            <%= action_icon({:type => "delete", :class => "has_go_tip_right", :title => "Cannot delete the only stage in a pipeline", :disabled => true}) %>
                            <!-- <span class="icon_cannot_remove has_go_tip_right" title=""></span> -->
                        <% else %>
                            <% unique_stage_delete_id = random_dom_id("delete_stage_") %>
                            <%= form_for stage_config, :as => :stage_config, :url => {:action => "destroy", :stage_name => stage_config.name()},
                                        :html => {:id => "#{unique_stage_delete_id}", :method => :delete} do |f| %>
                                <%= md5_field %>
                                <span class="icon_remove delete_parent" id="trigger_<%= unique_stage_delete_id %>">
                                    <%= render :partial => 'admin/shared/submit_with_prompt.html', :locals => {:scope => {:button_id => "trigger_#{unique_stage_delete_id}", :message => "Are you sure you want to delete the stage '#{stage_config.name()}' ? ", :on_confirmation_js => "$('#{"#{unique_stage_delete_id}"}').submit()"}} %>
                                </span>
                            <% end %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
            <tr>
                <td>&nbsp;</td>
                <td colspan="4">
                    <a class="add_link" href="#" onclick="ModalBoxWhichClosesAutoCompleteDropDownBeforeClosing.show('<%= admin_stage_new_path -%>', {overlayClose: false, title: 'Add Stage'})"><%= l.string("ADD_NEW_STAGE") %></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
<% end %>
</div>
<script type="text/javascript">
    Util.on_load(function() {
        var hasSwitchedToTemplate = false;
        setConfigurationType = function(element, isFirstTime) {
            var selected = jQuery(element).val();
            if (selected == "<%=com.thoughtworks.go.config.PipelineConfig::CONFIGURATION_TYPE_STAGES%>") {
                showElement(jQuery("#select_template_container"), false);
                showElement(jQuery("#stages_list_container"), true);
            } else if (selected == "<%=com.thoughtworks.go.config.PipelineConfig::CONFIGURATION_TYPE_TEMPLATE%>") {
                showElement(jQuery("#select_template_container"), true);
                showElement(jQuery("#stages_list_container"), false);
                if (!isFirstTime) {
                    hasSwitchedToTemplate = true;
                }
            }
        };
        setConfigurationType(jQuery("input:[name='pipeline[configurationType]']:checked"), true);

        jQuery("input:[name='pipeline[configurationType]']").click(function() {
            setConfigurationType(this, false);
        });

        new ViewTemplate("<%= config_view_templates_show_path(:name => "__template_name__") %>").addListener('a.view_template_link');

        jQuery("#select_template").change(function() {
            var templatized_template_url = "<%= template_edit_path(:pipeline_name => "__template_name__" ,:stage_parent => "templates", :current_tab => 'general') %>";
            var constructed_url = replace_url_with_selected_template(templatized_template_url);
            jQuery(".edit_template_link").attr("href", constructed_url);
        });

        function replace_url_with_selected_template(templatized_template_url) {
            return templatized_template_url.replace("__template_name__", selected_template_name());
        }

        function selected_template_name() {
            return jQuery("#select_template").val();
        }
    });
    AjaxForm.error_box_selector = '#MB_content';
</script>