server/webapp/WEB-INF/rails.new/config/routes.rb
  get "admin/package_repositories/:plugin/config/" => "admin/package_repositories#plugin_config", constraints: {:plugin => ALLOW_DOTS}, as: :package_repositories_plugin_config
  get "admin/package_repositories/:id/:plugin/config/" => "admin/package_repositories#plugin_config_for_repo", constraints: {:plugin => ALLOW_DOTS}, as: :package_repositories_plugin_config_for_repo

  get "admin/pipelines/:pipeline_name/materials/pluggable_scm/show_existing" => "admin/materials/pluggable_scm#show_existing", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_show_existing
  post "admin/pipelines/:pipeline_name/materials/pluggable_scm/choose_existing" => "admin/materials/pluggable_scm#choose_existing", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_choose_existing
  get "admin/pipelines/:pipeline_name/materials/pluggable_scm/new/:plugin_id" => "admin/materials/pluggable_scm#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, plugin_id: ALLOW_DOTS}, as: :admin_pluggable_scm_new
  post "admin/pipelines/:pipeline_name/materials/pluggable_scm/:plugin_id" => "admin/materials/pluggable_scm#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, plugin_id: ALLOW_DOTS}, as: :admin_pluggable_scm_create
  get "admin/pipelines/:pipeline_name/materials/pluggable_scm/:finger_print/edit" => "admin/materials/pluggable_scm#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_edit
  put "admin/pipelines/:pipeline_name/materials/pluggable_scm/:finger_print" => "admin/materials/pluggable_scm#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_update
  post "admin/materials/pluggable_scm/check_connection/:plugin_id" => "admin/materials/pluggable_scm#check_connection", constraints: {plugin_id: ALLOW_DOTS}, as: :admin_pluggable_scm_check_connection
  get "admin/materials/pluggable_scm/:scm_id/pipelines_used_in" => "admin/materials/pluggable_scm#pipelines_used_in", as: :scm_pipelines_used_in

  get 'agents/filter_autocomplete/:action' => 'agent_autocomplete#%{action}', constraints: {action: /resource|os|ip|name|status|environment/}, as: :agent_filter_autocomplete

  scope 'pipelines' do
    defaults :no_layout => true do
      get 'material_search' => 'pipelines#material_search'
      post 'show_for_trigger' => 'pipelines#show_for_trigger', as: :pipeline_show_with_option
      get ':pipeline_name/:pipeline_counter/build_cause' => 'pipelines#build_cause', constraints: PIPELINE_LOCATOR_CONSTRAINTS, as: :build_cause
    end

    get ':action' => 'pipelines#:action', constraints: {:action => /index|show|build_cause|select_pipelines/}
    post ':action' => 'pipelines#:action', constraints: {:action => /select_pipelines|show/}, as: :pipeline
  end

  get "pipelines(.:format)" => 'pipelines#index', defaults: {:format => "html"}, as: :pipeline_dashboard
  get 'home' => 'home#index'

  get "pipelines/value_stream_map/:pipeline_name/:pipeline_counter(.:format)" => "value_stream_map#show", constraints: {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}, defaults: {:format => :html}, as: :vsm_show
  get "materials/value_stream_map/:material_fingerprint/:revision(.:format)" => "value_stream_map#show_material", defaults: {:format => :html}, constraints: {:revision => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/}, as: :vsm_show_material

  scope 'compare' do
    get ':pipeline_name/:from_counter/with/:to_counter' => 'comparison#show', constraints: {from_counter: PIPELINE_COUNTER_FORMAT, to_counter: PIPELINE_COUNTER_FORMAT, pipeline_name: PIPELINE_NAME_FORMAT}, as: :compare_pipelines
    get ':pipeline_name/page/:page' => 'comparison#page', constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :compare_pipelines_page
    get ':pipeline_name/list/compare_with/:other_pipeline_counter' => 'comparison#list', constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, format: 'json', as: :compare_pipelines_list
    get ':pipeline_name/timeline/:page' => 'comparison#timeline', constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :compare_pipelines_timeline
  end

  get 'failures/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter/:job_name/:suite_name/:test_name' => 'failures#show', constraints: STAGE_LOCATOR_CONSTRAINTS, :no_layout => true, as: :failure_details_internal

  get 'server/messages.json' => 'server#messages', :format => "json", as: :global_message

  scope 'config_view' do
    get "templates/:name" => "config_view/templates#show", as: :config_view_templates_show, constraints: {name: TEMPLATE_NAME_FORMAT}
  end

  defaults :no_layout => true do
    get 'materials/:id.xml' => 'application#unresolved', as: :material
    get 'materials/:materialId/changeset/:modificationId.xml' => 'application#unresolved', as: :modification
  end

  scope 'environments' do
    defaults :no_layout => true do
      post "create" => 'environments#create', as: :environment_create
      get "new" => 'environments#new', as: :environment_new
      put ":name" => 'environments#update', constraints: ENVIRONMENT_NAME_CONSTRAINT, as: :environment_update

      [:pipelines, :agents, :variables].each do |action|
        get ":name/edit/#{action}" => "environments#edit_#{action}", constraints: ENVIRONMENT_NAME_CONSTRAINT, as: "environment_edit_#{action}"
      end
    end
    get ":name/show" => 'environments#show', constraints: ENVIRONMENT_NAME_CONSTRAINT, as: :environment_show
  end
  match "environments(.:format)" => 'environments#index', defaults: {:format => :html}, via: [:post, :get], as: :environments

  scope :api, as: :apiv1, format: false do
    api_version(:module => 'ApiV1', header: {name: 'Accept', value: 'application/vnd.go.cd.v1+json'}) do
      resources :backups, only: [:create], constraints: HeaderConstraint.new

      resources :users, param: :login_name, only: [:create, :index, :show, :destroy], constraints: {login_name: /(.*?)/} do
        patch :update, on: :member
      end

      namespace :elastic do
        resources :profiles, param: :profile_id, only: [:create, :index, :show, :destroy, :update], constraints: {profile_id: ELASTIC_AGENT_PROFILE_ID_FORMAT}
      end

      namespace :admin do
        resources :repositories, param: :repo_id, only: [:show, :index, :destroy, :create, :update], constraints: {repo_id: ALLOW_DOTS}
        resources :environments, param: :name, only: [:show, :destroy, :create, :update, :index], constraints: {:name => ENVIRONMENT_NAME_FORMAT} do
          patch on: :member, action: :patch
          put on: :member, action: :put
        end
        get 'environments/:name/withremote' => 'environments_with_remote#show',constraints: {:name => ENVIRONMENT_NAME_FORMAT}


        post 'encrypt', controller: :encryption, action: :encrypt_value
        resources :packages, param: :package_id, only: [:show, :destroy, :index, :create, :update], constraints: {package_id: ALLOW_DOTS}
        namespace :internal do
          post :material_test, controller: :material_test, action: :test, as: :material_test
          controller :package_repository_check_connection do
            post :repository_check_connection, [action: :repository_check_connection]
            post :package_check_connection, [action: :package_check_connection]
          end
          resources :pipelines, only: [:index]
          resources :resources, only: [:index]
          resources :environments, only: [:index]
          resources :command_snippets, only: [:index]
        end
        resources :scms, param: :material_name, controller: :pluggable_scms, only: [:index, :show, :create, :update], constraints: {material_name: ALLOW_DOTS}
      end

      get 'stages/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter' => 'stages#show', constraints: {pipeline_name: PIPELINE_NAME_FORMAT, pipeline_counter: PIPELINE_COUNTER_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_counter: STAGE_COUNTER_FORMAT}, as: :stage_instance_by_counter_api
      get 'stages/:pipeline_name/:stage_name' => 'stages#history', constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT}, as: :stage_history_api

      get 'dashboard', controller: :dashboard, action: :dashboard, as: :show_dashboard

      get 'version', controller: :version, action: :show, as: :version

      get 'version_infos/stale', controller: :version_infos, action: :stale, as: :stale_version_info
      patch 'version_infos/go_server', controller: :version_infos, action: :update_server, as: :update_server_version_info

      match '*url', via: :all, to: 'errors#not_found'
    end
  end

  scope :api, as: :apiv2, format: false do
    api_version(:module => 'ApiV2', header: {name: 'Accept', value: 'application/vnd.go.cd.v2+json'}) do
      namespace :admin do
        resources :pipelines, param: :pipeline_name, only: [:show, :update, :create, :destroy], constraints: {pipeline_name: PIPELINE_NAME_FORMAT}
        resources :templates, param: :template_name, except: [:new, :edit], constraints: {template_name: TEMPLATE_NAME_FORMAT}
        resources :plugin_info, controller: 'plugin_infos', param: :id, only: [:index, :show], constraints: {id: PLUGIN_ID_FORMAT}
      end

      match '*url', via: :all, to: 'errors#not_found'
    end
  end

  scope :api, as: :apiv3, format: false do
    api_version(:module => 'ApiV3', header: {name: 'Accept', value: 'application/vnd.go.cd.v3+json'}) do
      namespace :admin do
        resources :pipelines, param: :pipeline_name, only: [:show, :update, :create, :destroy], constraints: {pipeline_name: PIPELINE_NAME_FORMAT}
        resources :templates, param: :template_name, except: [:new, :edit], constraints: {template_name: TEMPLATE_NAME_FORMAT}
      end

      match '*url', via: :all, to: 'errors#not_found'
    end
  end

  scope :api, as: :apiv4, format: false do
    api_version(:module => 'ApiV4', header: {name: 'Accept', value: 'application/vnd.go.cd.v4+json'}) do

server/webapp/WEB-INF/rails.new/app/controllers/comparison_controller.rb
##########################GO-LICENSE-START################################
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

class ComparisonController < ApplicationController
  include ComparisonHelper
  layout :determine_layout

  PAGE_SIZE = 10

  def show
    redirect_to compare_pipelines_path(:pipeline_name => params[:pipeline_name], :to_counter => params[:to_counter], :from_counter => "1") and return if (params[:from_counter].to_i < 1)
    redirect_to compare_pipelines_path(:pipeline_name => params[:pipeline_name], :from_counter => params[:from_counter], :to_counter => "1") and return if (params[:to_counter].to_i < 1)
    
    @pipeline_name = params[:pipeline_name]

    @to_pipeline = load_pipeline_instance(@pipeline_name, params[:to_counter].to_i)
    return unless @to_pipeline

    @from_pipeline = load_pipeline_instance(@pipeline_name, params[:from_counter].to_i)
    return unless @from_pipeline

    @mingle_config = mingle_config_service.mingleConfigForPipelineNamed(@pipeline_name, current_user, result = HttpLocalizedOperationResult.new)
    return render_localized_operation_result(result) unless result.isSuccessful()

    revisions = changeset_service.revisionsBetween(@pipeline_name, @from_pipeline.getCounter(), @to_pipeline.getCounter(), current_user, result = HttpLocalizedOperationResult.new, true, show_bisect?) || {}
    @material_revisions = revisions.find_all { | material | material.getMaterialType() != "Pipeline" }
    @dependency_material_revisions = revisions.find_all { | material | material.getMaterialType() == "Pipeline" }

    @cruise_config = go_config_service.getCurrentConfig()

    render_localized_operation_result(result) unless result.isSuccessful()
  end

  def list
    @pipeline_instances = pipeline_history_service.findMatchingPipelineInstances(params[:pipeline_name], params[:q], PAGE_SIZE, current_user, HttpLocalizedOperationResult.new)
  end

  def timeline
    page = params[:page] || 1
    @pipeline_instances = pipeline_history_service.findPipelineInstancesByPageNumber(params[:pipeline_name],page.to_i,PAGE_SIZE, CaseInsensitiveString.str(current_user.getUsername()))
  end

  private

  def load_pipeline_instance(pipeline_name, counter)
    pipeline = pipeline_history_service.findPipelineInstance(pipeline_name, counter, current_user, result = HttpOperationResult.new)
    unless result.canContinue()
      render_operation_result(result)
      return nil
    end
    pipeline
  end

  def determine_layout
    %w(show).include?(action_name) ? "comparison" : false
  end
end

server/webapp/WEB-INF/rails.new/app/helpers/comparison_helper.rb
##########################GO-LICENSE-START################################
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

module ComparisonHelper

  def pipeline_compare_href pipeline_name, from_counter, to_counter
    if (from_counter > to_counter)
      return pipeline_compare_href pipeline_name, to_counter, from_counter
    end
    compare_pipelines_path(:pipeline_name => pipeline_name, :from_counter => from_counter, :to_counter => to_counter)
  end

  def any_match?(pattern, *values)
    regex = /#{pattern}/i
    values.compact.any? { |s| s =~ regex }
  end

  def compare_pipeline_pagination_handler page, suffix
    dom_id = "pim_pages_#{page.getLabel()}"
    url = compare_pipelines_timeline_path(:page => page.getNumber(),:other_pipeline_counter => params[:other_pipeline_counter], :suffix => suffix)
    <<END
    <a href="#" id="#{dom_id}">#{page.getLabel()}</a>
    <script type="text/javascript">
        Util.click_load({target: '##{dom_id}', url: '#{url}', update: '#modal_timeline_container', spinnerContainer: 'pagination_bar'});
    </script>
END
  end

  def show_bisect?
    params[:show_bisect] == true.to_s
  end
end

server/webapp/WEB-INF/rails.new/app/views/comparison/_bisect_warning.html.erb
<%- if scope[:to_pipeline].isBisect() || scope[:from_pipeline].isBisect() -%>
    <div class="information">
        <%- if params[:show_bisect] == true.to_s -%>
            <div class="warning">
                <%= l.string("SHOWING_BISECT_DIFF") -%>
            </div>
        <%- else -%>
            <div class="message">
                <span>
                    <%= l.string("SHOW_BISECT_DIFF_CONFIRMATION") -%>
                </span>
                <span class="prompt">
                    <%= link_to "Continue", compare_pipelines_path(:show_bisect => true), :class => :link_as_header_button -%>
                </span>
            </div>
        <%- end -%>
    </div>
<%- end -%>

server/webapp/WEB-INF/rails.new/app/views/comparison/_dependency_material_modifications_table.html.erb
<div class="material_title">
    <strong class="wrapped_word"> <%= "#{scope[:material].getTypeForDisplay()}" %> - <%= scope[:material].getDisplayName() -%></strong>
</div>
<table class="list_table dependency_material_modifications">
    <tr>
        <th class="dmr revision"><%= l.string("REVISION") -%></th>
        <th class="dmr label"><%= l.string("LABEL") -%></th>
        <th class="dmr completed_at"><%= l.string("COMPLETED_AT") -%></th>
    </tr>
    <% scope[:material_revision_in_diff_revisions].getModifications().each do |modification_in_diff_material_revision| %>
        <tr class="change">
            <td class="revision">
                <%== link_to(modification_in_diff_material_revision.getRevision(), path_for_stage(stage_identifier_for_locator(modification_in_diff_material_revision.getRevision()))) -%>
            </td>
            <td class="label">
                <%== stage_identifier = stage_identifier_for_locator(modification_in_diff_material_revision.getRevision())
                    link_to(modification_in_diff_material_revision.getPipelineLabel(), vsm_show_path(stage_identifier.getPipelineName(),stage_identifier.getPipelineCounter())) -%>
            </td>
            <td class="completed_at wrapped_word">
                <%= modification_in_diff_material_revision.getModifiedTime().iso8601 -%>
            </td>
        </tr>
    <% end %>
</table>

server/webapp/WEB-INF/rails.new/app/views/comparison/_material_modifications_table.html.erb
    <div class="material_title">
        <strong> <%== "#{scope[:material].getTypeForDisplay()}" %> - <%= "#{scope[:material].getLongDescription()}" -%></strong>
    </div>
    <table class="list_table material_modifications">
        <tr>
            <th class="revision"><%= l.string("REVISION") -%></th>
            <th class="modified_by"><%= l.string("MODIFIED_BY") -%></th>
            <th class="comment"><%= l.string("COMMENT") -%></th>
        </tr>
        <% scope[:material_revision_in_diff_revisions].getModifications().each do |modification_in_diff_material_revision| %>
            <tr class="change">
                <td class="revision wrapped_word">
                    <%= modification_in_diff_material_revision.getRevision() %>
                </td>
                <td class="modified_by">
                    <span class="wrapped_word"> <%= modification_in_diff_material_revision.getUserDisplayName() %></span>
                    <br/>
                    <span class="wrapped_word"> <%= modification_in_diff_material_revision.getModifiedTime().iso8601 %></span>
                </td>
                <td class="comment">
                    <%- if params[:pipeline_name] -%>
                        <%= render_comment(modification_in_diff_material_revision, params[:pipeline_name]) -%>
                    <%- else -%>
                        <%= modification_in_diff_material_revision.getComment() -%>
                    <%- end -%>
                </td>
            </tr>
        <% end %>
    </table>

server/webapp/WEB-INF/rails.new/app/views/comparison/_material_revision_tables.html.erb
<% scope[:scm_material_revisions].each do |material_revision_in_diff_revisions| %>
    <%- if scope[:draw_wrapper_div] -%>
        <div>
    <%- end -%>
    <%= render :partial => 'comparison/material_modifications_table.html', :locals => {:scope => {:material => material_revision_in_diff_revisions.getMaterial(), :material_revision_in_diff_revisions => material_revision_in_diff_revisions}} %>
    <%- if scope[:draw_wrapper_div] -%>
        </div>
    <%- end -%>
<% end %>
<% scope[:dependency_material_revisions].each do |material_revision_in_diff_revisions| %>
    <%- if scope[:draw_wrapper_div] -%>
        <div>
    <%- end -%>
    <%= render :partial => 'comparison/dependency_material_modifications_table.html', :locals => {:scope => {:material => material_revision_in_diff_revisions.getMaterial(), :material_revision_in_diff_revisions => material_revision_in_diff_revisions}} %>
    <%- if scope[:draw_wrapper_div] -%>
        </div>
    <%- end -%>
<% end %>

server/webapp/WEB-INF/rails.new/app/views/comparison/_pipeline_instances_drop_down.html.erb
<% scope[:pipeline_instances].each do |pipeline_instance| %>
    <div>
        <span class="stages stages_with_pipeline_counter pim_dropdown" style="width: 98%;">
            <div class="stage_bar_pipeline_counter" style="width: 3%;">
                <%= pipeline_instance.getCounter() -%>
            </div>
            <% pipeline_instance.getStageHistory().each do |sim_for_pipeline|
                scope[:html_options] = stage_bar_options(sim_for_pipeline) %>
                <div style='width: <%= stage_width_percent(pipeline_instance.numberOfStages(), false, 95) %>' class="stage">
                    <div class="stage_bar_wrapper">
                        <% if placeholder_stage?(sim_for_pipeline) %>
                            <div <%= scope[:html_options] -%>><%= check_for_cancelled_contents(sim_for_pipeline.getState()) %></div>
                        <% elsif pipeline_instance.isBisect() %>
                            <div class="text_in_dropdown disabled_text_in_dropdown"><%= l.string("BISECT_TRIGGERED_PIPELINE") %></div>
                        <% else %>
                            <a href="<%= pipeline_compare_href(scope[:pipeline_name], scope[:fixed_pipeline_counter], pipeline_instance.getCounter()) -%>" <%= scope[:html_options] -%> id="<%= "stage_detail_#{scope[:suffix]}_#{pipeline_instance.getCounter()}" %>">
                                <%= check_for_cancelled_contents(sim_for_pipeline.getState()) %><span><span></span></span>
                            </a>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </span>
    </div>
<% end %>
<% if scope[:pipeline_instances].getPagination().getCurrentPage() == scope[:pipeline_instances].getPagination().getLastPage() %>
    <div class="text_in_dropdown">
        <a href="<%= pipeline_compare_href(scope[:pipeline_name], scope[:fixed_pipeline_counter], 0) -%>" id="<%= "stage_detail_#{scope[:suffix]}_0" %>">
            <%= l.string("SINCE_CREATION") %>
        </a>
    </div>
<% end %>

<% if scope[:pipeline_instances].getPagination().getTotalPages() > 0 %>
    <div class="pagination">
        <% scope[:pipeline_instances].getPagination().getPages().each do |pages| %>
            <% if pages.isDots() %>
                <span>...</span>
            <% else %>
                <% unless pages.isCurrent() %>
                    <a href="javascript:void(0);" id="<%= scope[:dom_id] = "pipeline_history_#{scope[:suffix]}_#{pages.getLabel()}" %>"><%= pages.getLabel() %></a>
                    <script type='text/javascript'>
                        ComparePipelines.bindPagesLink('<%= scope[:dom_id] %>',
                                "<%= compare_pipelines_page_path(:page => page_num=pages.getNumber(), :selected => scope[:selected_pipeline_counter], :fixed_pipeline_counter => scope[:fixed_pipeline_counter], :suffix => scope[:suffix]) -%>",
                                <%= page_num%>);
                    </script>
                <% else %>
                    <span class="current_page" id="<%= scope[:dom_id] = "pipeline_history_#{scope[:suffix]}_#{pages.getLabel()}" %>"><%= pages.getLabel() %></span>
                <% end %>
            <% end %>
        <% end %>
    </div>
<% end %>

server/webapp/WEB-INF/rails.new/app/views/comparison/_stage_bar_without_controls.html.erb
<div class="compare_pipeline_page pipeline">
    <div class="current_instance" id='compare_pipeline_<%= scope[:suffix] %>'>
        <%= text_field_tag "#{scope[:suffix]}_pipeline", scope[:pipeline].getLabel(), :class => "compare_pipeline_input" -%>
        <div class="autocomplete"></div>
        <div class="enhanced_dropdown <%= scope[:suffix]%> hidden">
            <div class="compare_search_instructions">
                <p><%=l.string("SEARCH_PIPELINE_INSTRUCTIONS")-%></p>
                <p><%=l.string("OR")%></p>
                <p><a class="more_pipelines" id="browse_timeline_link_<%= scope[:suffix]%>">
                    <%=l.string("BROWSE_TIMELINE")%>
                 </a></p>
            </div>
        </div>
    </div>
    <% if scope[:pipeline].isBisect() && !show_bisect? %>
        <div class="pipeline_counter_information">
            <%= l.string("NO_COMPARISON_FOR_BISECT") %>
        </div>
    <% else %>
        <div class="selected_pipeline_<%= scope[:suffix] -%> stages">
            <div class="pipeline_details">
                <%= render :partial => "stage_bar.html", :locals => {:scope => {:pipeline => scope[:pipeline]}} -%>
            </div>
        </div>
    <% end %>
</div>

<script type="text/javascript">
    Util.on_load(function() {
        var pipelineSelector = "#<%= scope[:suffix] -%>_pipeline";
        jQuery(pipelineSelector).autocomplete("<%= compare_pipelines_list_path(:pipeline_name => scope[:pipeline].name(), :other_pipeline_counter => scope[:fixed_pipeline].getCounter()) -%>", {
            minChars: 1,
            width: 500,
            scrollHeight: 500,
            matchContains: "word",
            selectFirst: false,
            autoFill: false,
            delay: 1000,
            cacheLength: 0,
            multiClickTrigger: false,
            formatItem: function(row, i, max) {
                return row;
            },
            formatMatch: function(row, i, max) {
                return "";
            },
            formatResult: function(row) {
                return row.value;
            },
            parse: function(data) {
                return data.html;
            },
            dataType: 'json',
            highlight: function(value, term) {
                return value;//no-op
            }
        });
        jQuery(pipelineSelector).result(function(event, data, formatted) {
            var dest = compare_path("<%= scope[:suffix] %>", formatted, "<%= scope[:fixed_pipeline].getCounter() %>");
            if (formatted == -1) { // indicates no match, see list.json.erb
                resetField(event.target);
            } else {
                window.location.href = dest;
            }
        });
        jQuery(pipelineSelector).blur(function(event) {
            var val = jQuery.trim(jQuery(event.target).val());
            if (val == "" || val != '<%= scope[:pipeline].getLabel() %>') {
                resetField(event.target);
            }
        });
        function resetField(field) {
            jQuery(field).val('<%= scope[:pipeline].getLabel() %>');
        }

        ;
        function compare_path(suffix, counter, fixed_counter) {
            if (suffix == "from") {
                var from_counter = counter;
                var to_counter = fixed_counter;
            } else {
                var from_counter = fixed_counter;
                var to_counter = counter;
            }
            return "/go/compare/<%= params[:pipeline_name] %>/" + from_counter + "/with/" + to_counter;
        }

        var instructionsPopup = new MicroContentPopup(jQuery('.enhanced_dropdown.<%= scope[:suffix]%>').get(0), new MicroContentPopup.NoOpHandler());
        var instructionsPopupShower = new MicroContentPopup.ClickShower(instructionsPopup);
        jQuery(pipelineSelector).bind('keypress', function(event){
            instructionsPopupShower.close();
        });
        instructionsPopupShower.bindShowButton( jQuery(pipelineSelector).get(0));

        jQuery("#browse_timeline_link_<%= scope[:suffix]%>").click(function(event) {
           Modalbox.show('<%= compare_pipelines_timeline_path(:pipeline_name => scope[:pipeline].name(), :page => 1, :other_pipeline_counter => scope[:fixed_pipeline].getCounter(), :suffix => scope[:suffix]) -%>',
                {
                    overlayClose: false,
                    title: "<%=l.string("SELECT_PIPELINE_TO_COMPARE")%>"
                });
        });
    });
</script>

server/webapp/WEB-INF/rails.new/app/views/comparison/list.json.erb
{
    "html" : [
    <% if @pipeline_instances.empty? %>
    {
        "data": <%= render_json :text => "<div class='no_results'>No matching results</div>" -%>,
        "value": "-1",
        "result": ""
    }
    <% else %>
        <% @pipeline_instances.each_with_index do |pim, i| %>
            <%== i > 0 ? "," : "" %>
            {
                "data": <%== render_json :partial => "pipeline_autocomplete_list_entry.html.erb", :locals => {:scope => {:pipeline => pim}} -%>,
                "value": "<%== pim.getCounter %>",
                "result": "<%== pim.getLabel %>"
            }
        <% end %>
    <% end %>
    ]
}

server/webapp/WEB-INF/rails.new/app/views/comparison/timeline.html.erb
<div id="modal_timeline_container">
    <%= render :partial => "comparison/modal_timeline", :locals => {:scope => {:pipeline_instances => @pipeline_instances, :suffix => params[:suffix]}} %>
</div>