server/webapp/WEB-INF/rails.new/config/routes.rb
##########################GO-LICENSE-START################################
# Copyright 2016 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

Go::Application.routes.draw do
  mount JasmineRails::Engine => '/jasmine-specs', as: :jasmine_old if defined?(JasmineRails)
  mount JasmineRails::Engine => '/jasmine-specs-new', as: :jasmine_new if defined?(JasmineRails)

  unless defined?(CONSTANTS)
    ELASTIC_AGENT_PROFILE_ID_FORMAT = USER_NAME_FORMAT = GROUP_NAME_FORMAT = TEMPLATE_NAME_FORMAT = PIPELINE_NAME_FORMAT = STAGE_NAME_FORMAT = ENVIRONMENT_NAME_FORMAT = /[\w\-][\w\-.]*/
    JOB_NAME_FORMAT = /[\w\-.]+/
    PIPELINE_COUNTER_FORMAT = STAGE_COUNTER_FORMAT = /-?\d+/
    NON_NEGATIVE_INTEGER = /\d+/
    PIPELINE_LOCATOR_CONSTRAINTS = {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}
    STAGE_LOCATOR_CONSTRAINTS = {:stage_name => STAGE_NAME_FORMAT, :stage_counter => STAGE_COUNTER_FORMAT}.merge(PIPELINE_LOCATOR_CONSTRAINTS)
    ENVIRONMENT_NAME_CONSTRAINT = {:name => ENVIRONMENT_NAME_FORMAT}
    PLUGIN_ID_FORMAT = /[\w\-.]+/
    ALLOW_DOTS = /[^\/]+/
    CONSTANTS = true
  end

  mount Oauth2Provider::Engine => '/oauth', :as => :oauth_engine

  root 'welcome#index' # put to get root_path. '/' is handled by java.

  get "about", controller: :about, action: :show, as: :about

  get "admin/pipelines/snippet" => "admin/pipelines_snippet#index", as: :pipelines_snippet
  get "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_show
  get "admin/pipelines/snippet/:group_name/edit" => "admin/pipelines_snippet#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_edit
  put "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_update

  get 'admin/backup' => 'admin/backup#index', as: :backup_server
  post 'admin/backup' => 'admin/backup#perform_backup', as: :perform_backup

  get "admin/plugins" => "admin/plugins/plugins#index", as: :plugins_listing
  post 'admin/plugins' => 'admin/plugins/plugins#upload', as: :upload_plugin
  get 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#edit_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :edit_settings
  post 'admin/plugins/settings/:plugin_id' => 'admin/plugins/plugins#update_settings', constraints: {plugin_id: ALLOW_DOTS}, as: :update_settings

  ["svn", "git", "hg", "p4", "dependency", "tfs", "package"].each do |material_type|
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/new" => "admin/materials/#{material_type}#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_new"
    post "admin/pipelines/:pipeline_name/materials/#{material_type}" => "admin/materials/#{material_type}#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_create"
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print/edit" => "admin/materials/#{material_type}#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_edit"
    put "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print" => "admin/materials/#{material_type}#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_update"
  end
  defaults :no_layout => true do
    get "admin/pipelines/:pipeline_name/materials/dependency/pipeline_name_search" => "admin/materials/dependency#pipeline_name_search", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_pipeline_name_search
    get "admin/pipelines/:pipeline_name/materials/dependency/load_stage_names_for" => "admin/materials/dependency#load_stage_names_for", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_load_stage_names_for
  end
  get "admin/:stage_parent/:pipeline_name/materials" => "admin/materials#index", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_index
  delete "admin/:stage_parent/:pipeline_name/materials/:finger_print" => "admin/materials#destroy", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_delete

  get "admin/pipeline/new" => "admin/pipelines#new", as: :pipeline_new
  post "admin/pipelines" => "admin/pipelines#create", as: :pipeline_create
  get "admin/pipeline/:pipeline_name/clone" => "admin/pipelines#clone", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pipeline_clone
  post "admin/pipeline/save_clone" => "admin/pipelines#save_clone", as: :pipeline_save_clone
  get "admin/pipelines/:pipeline_name/pause_info.json" => "admin/pipelines#pause_info", :format => "json", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pause_info_refresh
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#edit", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#update", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_update

  get "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_listing
  put "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#use_template", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_use_template
  get "admin/:stage_parent/:pipeline_name/stages/new" => "admin/stages#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_new
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name" => "admin/stages#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_delete
  post "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/increment" => "admin/stages#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete

server/webapp/WEB-INF/rails.new/app/controllers/api_v1/admin/internal/pipelines_controller.rb
##########################################################################
# Copyright 2016 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

module ApiV1
  module Admin
    module Internal
      class PipelinesController < ApiV1::BaseController
        before_action :check_admin_user_or_group_admin_user_and_401

        def index
          pipelines = pipeline_config_service.viewableOrOperatableGroupsFor(current_user)

          json = ApiV1::Config::PipelineConfigsWithMinimalAttributesRepresenter.new(pipelines).to_hash(url_builder: self)

          render json_hal_v1: json
        end
      end
    end
  end
end

server/webapp/WEB-INF/rails.new/app/helpers/pipelines_helper.rb
##########################GO-LICENSE-START################################
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

module PipelinesHelper
  include RailsLocalizer
  include JavaImports
  include ERB::Util

  def stage_bar_url stage, action
    stage_id = stage.getIdentifier()
    stage.isScheduled() ? stage_detail_tab_path(:stage_name => stage_id.getStageName(), :stage_counter => stage_id.getStageCounter(), :pipeline_name => stage_id.getPipelineName(), :pipeline_counter => stage_id.getPipelineCounter(), :action => action) : "#"
  end

  def run_stage_label stage
    (stage.isScheduled() ? "rerun" : "trigger")
  end

  def trigger_message(actual_date_time, pim)
    if pim.class != com.thoughtworks.go.presentation.pipelinehistory.PreparingToScheduleInstance
      "(Triggered&nbsp;#{l.string('BY')}&nbsp;<span class='who'>#{h pim.getApprovedBy()}</span>&nbsp;<span class='time'></span><input type='hidden' value='#{actual_date_time}'/>)"
    else
    ""
    end
  end

  def trigger_message_with_formatted_date_time(date_time, who)
    on = "&nbsp;#{l.string("on")}&nbsp;<span class='time'>#{date_time.to_long_display_date_time}</span>"
    if who == GoConstants::DEFAULT_APPROVED_BY
      "<span class='label'>#{l.string("AUTO_TRIGGERED")}</span>#{on}".html_safe
    else
      "<span class='label'>#{l.string("Triggered")}</span>&nbsp;#{l.string("by")}&nbsp;<span class='who'>#{h who}</span>#{on}".html_safe
    end
  end

  def pipelines_pipeline_dom_id(pipeline_model)
    "pipeline_#{pipeline_name(pipeline_model)}_panel"
  end

  def pipelines_dom_id(pipeline_group_name)
    "pipeline_group_#{pipeline_group_name}_panel"
  end

  def pipeline_name pipeline_model
    pipeline_model.getLatestPipelineInstance().getName()
  end

  def material_type(material)
    dependency?(material) ? 'dependency' : 'scm'
  end

  def dependency?(material)
    material.is_a? DependencyMaterial
  end

  def revision_for(revision)
    if dependency?(revision.getMaterial())
      "#{revision.getRevision().getPipelineName()}/#{revision.getRevision().getPipelineCounter()}"
    else
      revision.getLatestShortRevision()
    end
  end

  def pipeline_instance_identifier(pim)
    "#{pim.getName()}_#{pim.getCounter()}"
  end

  def pipeline_build_cause_popup_id(pim)
    "changes_#{pipeline_instance_identifier(pim)}"
  end

  def build_cause_popup_id_for_pipeline_counter(counter, prefix = nil)
    "#{prefix}for_pipeline_#{counter}"
  end

  def url_for_pipeline_instance(pipeline, options = {})
    stage = pipeline.latestStage()
    stage_detail_tab_path(options.merge({:pipeline_name => pipeline.getName(), :pipeline_counter => pipeline.getCounter(), :stage_name => stage.getName(), :stage_counter => stage.getCounter(), :action => "pipeline"}))
  end

  def url_for_pipeline_value_stream_map(pipeline, options = {})
    vsm_show_path(options.merge({:pipeline_name => pipeline.getName(), :pipeline_counter => pipeline.getCounter(), :action => "show"}))
  end

  def url_for_dmr(dmr)
    stage_detail_tab_path({:pipeline_name => dmr.getPipelineName(), :pipeline_counter => dmr.getPipelineCounter(), :stage_name => dmr.getStageName(), :stage_counter => dmr.getStageCounter(), :action => "pipeline"})
  end
end

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/_pipeline_navigation.html.erb
<ul>
    <li id="general"><%= link_to l.string("GENERAL_OPTIONS"), pipeline_edit_path(:current_tab => 'general') %></li>
    <li id="project_management"><%= link_to l.string("PROJECT_MANAGEMENT"), pipeline_edit_path(:current_tab => 'project_management') %></li>
    <li id="materials"><%= link_to 'Materials', admin_material_index_path(:current_tab => 'materials') %></li>
    <li id="stages">
        <%= link_to "#{l.string("STAGES")}", admin_stage_listing_path(:stage_parent => "pipelines", :current_tab => "stages") %>
    </li>
    <li id="environment_variables"><%= link_to l.string("ENVIRONMENT_VARIABLES"), pipeline_edit_path(:current_tab => 'environment_variables') %></li>
    <li id="parameters"><%= link_to l.string("PARAMETERS"), pipeline_edit_path(:current_tab => 'parameters') %></li>
</ul>

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/_wizard_step_title.html.erb
<h2 class="section_title">
  <span class="step_number"><%= l.string("WIZARD_STEP", [scope[:step]]) -%> </span><%= scope[:title] -%>
</h2>

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/environment_variables.html.erb
<div class="config-container config-env-variables">
<a name="plain_section"><h3 class="section-title"><%= l.string("ENVIRONMENT_VARIABLES") %></h3></a>
<span title="<%= l.string("TOOLTIP_ENVIRONMENT_VARIABLES") -%>" class="contextual_help has_go_tip_right">&nbsp;</span>

<%= form_for @pipeline, :as => :pipeline, :url => pipeline_update_path(:pipeline_name => @pipeline.name(), :current_tab => 'environment_variables'), :html => {:method => :put, :id => "pipeline_edit_form"} do |f| %>
    <%= render partial: 'admin/shared/environment_variable_fieldset', locals: {
                                                                            form: f,
                                                                            collection: @pipeline.getPlainTextVariables(),
                                                                            collection_name: :variables,
                                                                            nested_name: 'pipeline>variables'
                                                                    } %>

    <h3><%= l.string("SECURE_ENVIRONMENT_VARIABLES") %></h3>
    <span title="<%= l.string("TOOLTIP_ENCRYPTED_ENVIRONMENT_VARIABLES") -%>" class="contextual_help has_go_tip_right">&nbsp;</span>
    <div class="fieldset">
        <%= render :partial => "admin/shared/name_value", :locals => {:scope => {:form => f, :collection => @pipeline.getSecureVariables(), :collection_name => :variables, :secure => true}} %>
        <div class='clear'></div>
    </div>

    <%= render :partial => "admin/shared/form_submit", :locals => {:scope => {:reset_url => pipeline_edit_path(:pipeline_name => params[:pipeline_name], :current_tab => 'environment_variables')}} %>
<% end %>
</div>

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/general.html.erb
<div class="config-container config-general">
<h3 class="section-title"><%= l.string("BASIC_SETTINGS") %></h3>

<%= form_for @pipeline, :as => :pipeline, :url => pipeline_update_path(:pipeline_name => @pipeline.name(), :current_tab => 'general'), :html => {:method => :put, :id => "pipeline_edit_form"} do |f| %>
    <%= md5_field %>
    <div class="fieldset">
        <div class="form_item">
            <div class="form_item_block required">
                <%= required_label(f, com.thoughtworks.go.config.PipelineConfig::NAME, l.string('PIPELINE_NAME')) -%>
                <%= f.text_field com.thoughtworks.go.config.PipelineConfig::NAME, :readonly => :readonly, :disabled=> :disabled -%>
                <%= error_message_on(@pipeline, com.thoughtworks.go.config.PipelineConfig::NAME, :css_class => "form_error") %>
            </div>

            <div class="form_item_block required">
                <%= required_label(f, com.thoughtworks.go.config.PipelineConfig::LABEL_TEMPLATE, l.string('LABEL_TEMPLATE')) -%>
                <%= f.text_field com.thoughtworks.go.config.PipelineConfig::LABEL_TEMPLATE -%>
                <div class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_LABEL_TEMPLATE") -%>"></div>
                <%= error_message_on(@pipeline, com.thoughtworks.go.config.PipelineConfig::LABEL_TEMPLATE, :css_class => "form_error") %>
            </div>

            <div class="form_item_block checkbox_row">
                <div class="checkbox_label_wrapper">
                    <%= f.check_box com.thoughtworks.go.config.PipelineConfig::LOCK -%>
                    <%= f.label com.thoughtworks.go.config.PipelineConfig::LOCK, l.string('AUTOMATIC_PIPELINE_LOCKING') -%>
                </div>
                <div class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_PIPELINE_LOCKING") -%>"></div>
                <%= error_message_on(@pipeline, com.thoughtworks.go.config.PipelineConfig::LOCK, :css_class => "form_error") %>
            </div>

            <% if @pipeline.hasTemplate() -%>
                <%- first_stage_of_template = first_stage_of_template(@cruise_config, @pipeline.getTemplateName()) -%>
                <%= f.fields_for :approval, first_stage_of_template.getApproval do |approval| %>
                    <div class="form_item_block checkbox_row">
                        <div class="checkbox_label_wrapper">
                            <%= approval.check_box com.thoughtworks.go.config.Approval::TYPE, {:disabled => :disabled, :name => :not_to_be_submitted}, com.thoughtworks.go.config.Approval::SUCCESS, com.thoughtworks.go.config.Approval::MANUAL -%>
                            <%= approval.label com.thoughtworks.go.config.Approval::TYPE, l.string('AUTOMATIC_PIPELINE_SCHEDULING') -%>
                            <span class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_AUTOMATIC_PIPELINE_SCHEDULING") -%>"></span>
                        </div>
                        <span class="inline_instruction"><%= l.string("INLINE_INSTRUCTION_AUTOMATIC_PIPELINE_SCHEDULING") -%></span>
                    </div>
                <% end -%>
            <% else -%>
                <%= f.fields_for :approval, @pipeline.get(0).getApproval do |approval| %>
                    <div class="form_item_block checkbox_row">
                        <div class="checkbox_label_wrapper">
                            <%= approval.check_box com.thoughtworks.go.config.Approval::TYPE, {}, com.thoughtworks.go.config.Approval::SUCCESS, com.thoughtworks.go.config.Approval::MANUAL -%>
                            <%= approval.label com.thoughtworks.go.config.Approval::TYPE, l.string('AUTOMATIC_PIPELINE_SCHEDULING') -%>
                        </div>
                        <div class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_AUTOMATIC_PIPELINE_SCHEDULING") -%>"></div>
                    </div>
                <% end -%>
            <% end -%>
        </div>
    </div>
    <h3><%= l.string("TIMER_SETTINGS") %></h3>
    <div class="fieldset">
        <div class="form_item">

            <%= f.fields_for com.thoughtworks.go.config.PipelineConfig::TIMER_CONFIG, @pipeline.timer do |t| %>
                <div class="form_item_block timer_block">
                    <%= t.label com.thoughtworks.go.config.TimerConfig::TIMER_SPEC, l.string('CRON_TIMER_SPECIFICATION') -%>
                    <%= t.text_field com.thoughtworks.go.config.TimerConfig::TIMER_SPEC -%>
                    <div class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_CRON_TIMER_SPECIFICATION") -%>"></div>
                    <%= error_message_on(@pipeline.getTimer(), com.thoughtworks.go.config.TimerConfig::TIMER_SPEC, :css_class => "form_error") %>
                </div>
                <div class="form_item_block checkbox_row">
                    <div class="checkbox_label_wrapper">
                        <%= t.check_box com.thoughtworks.go.config.TimerConfig::TIMER_ONLY_ON_CHANGES -%>
                        <%= t.label com.thoughtworks.go.config.TimerConfig::TIMER_ONLY_ON_CHANGES, l.string('ONLY_ON_CHANGES'), :id => "pipeline_timer_onlyOnChanges_label" -%>
                    </div>
                    <div class="contextual_help has_go_tip_right" title="<%= l.string("TOOLTIP_ONLY_ON_CHANGES") -%>"></div>
                    <div class="inline_instruction"><%= l.string("NOTE_FOR_ONLY_ON_CHANGES") -%></div>
                </div>

            <% end %>

        </div>
    </div>

    <%= render :partial => 'shared/form_required_message.html', :locals => {:scope => {}} %>


    <%= render :partial => "admin/shared/form_submit", :locals => {:scope => {:reset_url => pipeline_edit_path(:pipeline_name => params[:pipeline_name], :current_tab => 'general')}} %>
    <%= render :partial => 'shared/convert_tool_tips.html', :locals => {:scope => {}} %>
<% end %>
</div>
<script type="text/javascript">
    var timeSpecTexbox = jQuery("#pipeline_timer_timerSpec");
    var onlyOnChangeCheckbox = jQuery("#pipeline_timer_onlyOnChanges");
    var onlyOnChangeLabel = jQuery("#pipeline_timer_onlyOnChanges_label");

    function enableCheckboxAndLabel() {
        onlyOnChangeCheckbox.removeAttr("disabled");
        onlyOnChangeLabel.removeClass("disabled");
    }

    function disableCheckboxAndLabel() {
        onlyOnChangeCheckbox.attr("disabled", "disabled");
        onlyOnChangeLabel.addClass("disabled");
    }

    Util.on_load(function() {
        if (timeSpecTexbox.val()) {
            enableCheckboxAndLabel();
        }
        else {
            disableCheckboxAndLabel();
        }
        timeSpecTexbox.on("keyup", function() {
            if (this.value == "") {
                disableCheckboxAndLabel();
            }
            else {
                enableCheckboxAndLabel();
            }
        });
    });
</script>

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/parameters.html.erb
<h3><%= l.string("PARAMETERS") %></h3>
<span title="<%= l.string("TOOLTIP_PARAMETERS") -%>" class="contextual_help has_go_tip_right">&nbsp;</span>

<%= form_for @pipeline, :as => :pipeline, :url => pipeline_update_path(:pipeline_name => @pipeline.name(), :current_tab => 'parameters'), :html => {:method => :put, :id => "pipeline_edit_form"} do |f| %>
    <div class="fieldset">
        <%= md5_field %>
        <%= register_defaultable_list("pipeline>params") %>
        <%= render :partial => "admin/shared/name_value", :locals => {:scope => {:form => f, :collection => @pipeline.getParams(), :collection_name => :params}} %>
         <div class="clear"></div>
    </div>
    <%= render :partial => "admin/shared/form_submit", :locals => {:scope => {:reset_url => pipeline_edit_path(:pipeline_name => params[:pipeline_name], :current_tab => 'parameters')}} %>
<% end %>

server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/pause_info.json.erb
{
    "pause_info_and_controls": {"html" : <%== render_json :partial => "shared/pause_info_and_control.html", :locals => {:scope => {:pause_info => @pause_info, :pipeline_name => @pipeline.name().to_s}} -%>}
}